[build]
  command = "yarn build"
  publish = "dist"
  environment = { NODE_VERSION = "16" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  skipPatterns = ["fonts.googleapis.com", "fonts.gstatic.com"]

[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    url = "https://www.martingredler.at"

[[plugins]]
package = "netlify-plugin-no-more-404"

[[plugins]]
package = "netlify-plugin-submit-sitemap"

[[plugins]]
package = "netlify-plugin-pushover"